config/routes.rb
Rails.application.routes.draw do
  resources :foos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foo.rb
class Foo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  add_flash_types :success, :error

  rescue_from ActionController::ParameterMissing, with: :missing_params

  def missing_params(exception)
    render json: { error: exception.message }, status: :unprocessable_entity
  end
  private :missing_params
end

app/controllers/foos_controller.rb
class FoosController < ApplicationController
  before_action :set_foo, only: [:show, :edit, :update, :destroy]

  # GET /foos
  # GET /foos.json
  def index
    @foos = Foo.all
  end

  # GET /foos/1
  # GET /foos/1.json
  def show
  end

  # GET /foos/new
  def new
    @foo = Foo.new
  end

  # GET /foos/1/edit
  def edit
  end

  # POST /foos
  # POST /foos.json
  def create
    @foo = Foo.new(foo_params)

    respond_to do |format|
      if @foo.save
        format.html { redirect_to @foo, notice: 'Foo was successfully created.' }
        format.json { render :show, status: :created, location: @foo }
      else
        format.html { render :new }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foos/1
  # PATCH/PUT /foos/1.json
  def update
    respond_to do |format|
      if @foo.update(foo_params)
        format.html { redirect_to @foo, notice: 'Foo was successfully updated.' }
        format.json { render :show, status: :ok, location: @foo }
      else
        format.html { render :edit }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foos/1
  # DELETE /foos/1.json
  def destroy
    @foo.destroy
    respond_to do |format|
      format.html { redirect_to foos_url, notice: 'Foo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foo
      @foo = Foo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foo_params
      params.fetch(:foo, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foos_helper.rb
module FoosHelper
end

app/views/foos/_form.html.erb
<%= form_with(model: foo, local: true) do |form| %>
  <% if foo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foo.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
      <% foo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foos/edit.html.erb
<h1>Editing Foo</h1>

<%= render 'form', foo: @foo %>

<%= link_to 'Show', @foo %> |
<%= link_to 'Back', foos_path %>

app/views/foos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foos.each do |foo| %>
      <tr>
        <td><%= link_to 'Show', foo %></td>
        <td><%= link_to 'Edit', edit_foo_path(foo) %></td>
        <td><%= link_to 'Destroy', foo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foo', new_foo_path %>

app/views/foos/new.html.erb
<h1>New Foo</h1>

<%= render 'form', foo: @foo %>

<%= link_to 'Back', foos_path %>

app/views/foos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_foo_path(@foo) %> |
<%= link_to 'Back', foos_path %>

app/views/home/index.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>


Create a new URL:<br>
<%= form_for(:url, url: "api/v1/urls#create") do |f| %>
  <%= f.label :url %>:
  <%= f.text_field :url %><br>

  <%= f.submit %>
<% end %>

Top <%= @urls.length %> URLs:
<table>
  <tr>
    <th>URL</th>
    <th>Slug</th>
    <th>Hit Count</th>
    <%@urls.each do |url| %>
    <tr>
      <th><%= url.path %></th>
      <th><%= url.slug %></th>
      <th><%= url.hit_count %></th>
    </tr>
    <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bitly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>